### ISSUE TITLE
Improve hex.info task output

### ISSUE THREAD

**Issue by lexmag** [hexpm/hex#171]
Currently `mix hex.info httpoison` gives the following output:
```
httpoison
  Config: {:httpoison, "~> 0.8.0"}
  Releases: 0.8.0, 0.7.5, 0.7.4, 0.7.3, 0.7.2, 0.7.1, 0.7.0, 0.6.2, 0.6.1, 0.6.0, 0.5.0, 0.4.3, 0.4.2, 0.4.1, 0.4.0, 0.3.2, 0.3.1, 0.3.0, 0.2.0

  Maintainers: Eduardo Gurgel Pinho
  Licenses: MIT
  Links:
    Github: https://github.com/edgurgel/httpoison

Yet Another HTTP client for Elixir powered by hackney
```
There are few things I think we could improve:
  1. Do not show first line: `httpoison` (seems very redundant, this what user provides as argument)
  2. Show only last 10 (other number?) releases
  3. Put description to the top (it is always very concise)

@ericmj, @josevalim, what are your thoughts?
